import type { CoercionMode } from "./coercion.js";
import type { Pass } from "./passes/index.js";
import type { PinCommentStyle } from "./passes/pin.js";

export type ActioTarget = "legacy" | "github-actions-native-dependencies-preview";

/**
 * Pin-on-compile policy. At `actio build`, pinnable `uses:` refs are rewritten to
 * an immutable SHA / digest with the original tag kept as a trailing comment.
 */
export interface PinConfig {
  /** Master switch. Default true. */
  enabled?: boolean;
  /** Pin third-party actions (any owner other than `actions`/`github`). Default true. */
  thirdParty?: boolean;
  /** Pin first-party actions (`actions/*`, `github/*`). Default false. */
  github?: boolean;
  /** Pin `uses: docker://img:tag` references. Default true. */
  docker?: boolean;
  /** Globs (matched against `owner/repo` or the full ref) always left on their tag. */
  allow?: string[];
  /** Trailing comment style for pinned refs. Default "tag". */
  comment?: PinCommentStyle;
}

/**
 * Shape of an `actio.config.{ts,js,mjs,cjs,json}` file. Every field is optional;
 * a missing field falls back to the built-in default (and any explicit CLI flag
 * overrides the value here). See `defineConfig` for type-safe authoring.
 */
export interface ActioConfig {
  /** Directory generated workflows are written to. Default ".github/workflows". */
  outDir?: string;
  /** Validate generated YAML against GitHub's workflow schema. Default true. */
  validate?: boolean;
  /**
   * Lint generated workflows with `actionlint`, mapping any finding back to its
   * `.actio.yml` source. `off` disables it (default); `warn` reports warnings
   * (exit 0); `error` fails the build (pairs well with `actio check` in CI).
   * This is output linting and is independent of the schema-gating `validate`
   * boolean. A missing `actionlint` binary is skipped gracefully.
   */
  lint?: "off" | "warn" | "error";
  /** Prepend the "generated by Actio" banner. Default true. */
  header?: boolean;
  /** Emit a sidecar `<name>.yml.map` source map next to each workflow. Default true. */
  sourceMap?: boolean;
  /**
   * Append an `actio-annotate` job that, on failure, maps the failed step back
   * to its `.actio.yml` source line and emits workflow annotations. Requires the
   * source map. Default true.
   */
  annotate?: boolean;
  /** Glob patterns of `.actio.yml` files to compile when none are passed on the CLI. */
  files?: string[];
  /** Alias for `files`. */
  include?: string[];
  /** Extra transform passes merged into the built-in pipeline (ordered by `runsAfter`). */
  passes?: Pass[];
  /**
   * Output target capability profile.
   * - `legacy`: emits standard workflows with no native dependency lock block.
   * - `github-actions-native-dependencies-preview`: emits a native `dependencies:` block.
   */
  target?: ActioTarget;
  /**
   * Global default mode for the injection-hoist security pass that defuses
   * `${{ }}` script-injection in `run:` blocks. Per-block `injection-hoist:`
   * knobs override this. Default "fix".
   */
  injectionHoist?: "fix" | "warn" | "error" | "off";
  /**
   * Severity for dead-code diagnostics on declared-but-unreferenced `params`,
   * `fragments`, and `executors`. `off` disables the check; `warn` reports
   * warnings (default); `error` escalates them to build failures (pairs well
   * with `actio check` in CI). Suppress a single symbol with a `# actio-keep`
   * comment on its declaration.
   */
  unusedSymbols?: "off" | "warn" | "error";
  /**
   * Global default mode for the YAML type-coercion guard that defends emitted
   * string scalars against YAML-1.1 coercion on the Actions runner (`no`→false,
   * `1:30`→90, `2024-01-01`→Date). `fix` single-quotes them, `warn` reports a
   * `yaml-coercion-trap` diagnostic, `off` disables it. An in-source root
   * `coercion:` key overrides this. Default "fix".
   */
  coercion?: CoercionMode;
  /**
   * Pin-on-compile policy. An object configures it granularly; the sugar `"all"`
   * pins everything (including first-party) and `"off"` disables pinning entirely.
   * Default: third-party + docker pinned, first-party left on-tag.
   */
  pin?: PinConfig | "all" | "off";
  /**
   * Inline step-level `artifacts:` macro config. `uploader` is the action ref
   * emitted for the trailing upload step (then pinned like any other ref under
   * pin policy). Default "actions/upload-artifact@v4".
   */
  artifacts?: { uploader?: string };
}

/** Identity helper that gives `actio.config.ts` authors full type-checking and inference. */
export function defineConfig(config: ActioConfig): ActioConfig {
  return config;
}
