import type { Pass } from "./passes/index.js";

/**
 * Shape of an `actio.config.{ts,js,mjs,cjs,json}` file. Every field is optional;
 * a missing field falls back to the built-in default (and any explicit CLI flag
 * overrides the value here). See `defineConfig` for type-safe authoring.
 */
export interface ActioConfig {
  /** Directory generated workflows are written to. Default ".github/workflows". */
  outDir?: string;
  /** Validate generated YAML against GitHub's workflow schema. Default true. */
  validate?: boolean;
  /** Prepend the "generated by Actio" banner. Default true. */
  header?: boolean;
  /** Emit a sidecar `<name>.yml.map` source map next to each workflow. Default true. */
  sourceMap?: boolean;
  /**
   * Append an `actio-annotate` job that, on failure, maps the failed step back
   * to its `.actio.yml` source line and emits workflow annotations. Requires the
   * source map. Default true.
   */
  annotate?: boolean;
  /** Glob patterns of `.actio.yml` files to compile when none are passed on the CLI. */
  files?: string[];
  /** Alias for `files`. */
  include?: string[];
  /** Extra transform passes merged into the built-in pipeline (ordered by `runsAfter`). */
  passes?: Pass[];
}

/** Identity helper that gives `actio.config.ts` authors full type-checking and inference. */
export function defineConfig(config: ActioConfig): ActioConfig {
  return config;
}
