import { type ToStringOptions, stringify } from "yaml";
import type { WorkflowData } from "./parser.js";

export interface EmitOptions {
  /** Prepend the "generated by Actio" banner. Default true. */
  header?: boolean;
  /** Source file name, referenced in the banner. */
  fileName?: string;
}

const STRINGIFY_OPTIONS: ToStringOptions = {
  // Never fold long lines — GitHub Actions YAML is read by humans and tools alike.
  lineWidth: 0,
  // Keep multi-line `run:` scripts as literal block scalars.
  blockQuote: "literal",
  // Default schema is YAML 1.2 core, so `on:` stays an unquoted string (not a boolean).
};

export function generatedHeader(fileName?: string): string {
  const src = fileName ? `\n# Source: ${fileName}` : "";
  return [
    "# Code generated by Actio. DO NOT EDIT.",
    `# Edit the .actio.yml source and run \`actio build\` instead.${src}`,
    "",
    "",
  ].join("\n");
}

export function emitYaml(data: WorkflowData, options: EmitOptions = {}): string {
  const body = stringify(data, STRINGIFY_OPTIONS);
  if (options.header === false) return body;
  return generatedHeader(options.fileName) + body;
}
