import { stringify, type ToStringOptions } from "yaml";
import { KEY_ORDER, type WorkflowData } from "./parser.js";

export interface EmitOptions {
  /** Prepend the "generated by Actio" banner. Default true. */
  header?: boolean;
  /** Source file name, referenced in the banner. */
  fileName?: string;
}

const STRINGIFY_OPTIONS: ToStringOptions = {
  // Never fold long lines — GitHub Actions YAML is read by humans and tools alike.
  lineWidth: 0,
  // Keep multi-line `run:` scripts as literal block scalars.
  blockQuote: "literal",
  // Default schema is YAML 1.2 core, so `on:` stays an unquoted string (not a boolean).
};

export function generatedHeader(fileName?: string): string {
  const src = fileName ? `\n# Source: ${fileName}` : "";
  return [
    "# Code generated by Actio. DO NOT EDIT.",
    `# Edit the .actio.yml source and run \`actio build\` instead.${src}`,
    "",
    "",
  ].join("\n");
}

export function emitYaml(data: WorkflowData, options: EmitOptions = {}): string {
  const body = stringify(toOrdered(data), STRINGIFY_OPTIONS);
  if (options.header === false) return body;
  return generatedHeader(options.fileName) + body;
}

/**
 * Re-key mappings into order-preserving Maps so `stringify` emits keys in author
 * order. JS objects hoist integer-like keys; yaml honors Map insertion order.
 * Pass-created objects lack KEY_ORDER and fall back to their own key order.
 */
function toOrdered(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(toOrdered);
  if (value && typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const recorded: string[] | undefined = (obj as Record<symbol, unknown>)[KEY_ORDER] as
      | string[]
      | undefined;
    const present = Object.keys(obj);
    const ordered = recorded
      ? [...recorded.filter((k) => k in obj), ...present.filter((k) => !recorded.includes(k))]
      : present;
    const map = new Map<string, unknown>();
    for (const k of ordered) map.set(k, toOrdered(obj[k]));
    return map;
  }
  return value;
}
