export { type ActioConfig, type ActioTarget, defineConfig } from "./config.js";
export {
  ActioError,
  type Diagnostic,
  type DiagnosticSource,
  formatDiagnostic,
  formatDiagnostics,
  formatGithubAnnotation,
  type Position,
  type Range,
  type Severity,
} from "./diagnostics.js";
export { type EmitOptions, emitYaml, generatedHeader } from "./emit.js";
export {
  cloneNode,
  conservativeTaint,
  deriveNode,
  type Job,
  type JobView,
  type Origin,
  originOf,
  type ParamType,
  recordOrigin,
  type Step,
  type StepView,
  type SymbolDef,
  type SymbolKind,
  type SymbolTable,
  seedOrigins,
  setOrigin,
  type TaintFacet,
  transformSteps,
  visitJobs,
  visitSteps,
  type Workflow,
  workflow,
} from "./ir.js";
export {
  type JobDefaultsInternalSnapshot,
  type ParseContext,
  type ParseContextInternal,
  type Path,
  parseActio,
  rangeOfPath,
  type WorkflowData,
} from "./parser.js";
export {
  ANNOTATE_ACTION,
  ANNOTATE_JOB_ID,
  annotate,
  applyDefaults,
  applyExecutor,
  applyPasses,
  builtinPasses,
  createRegistry,
  dynamicMatrix,
  EXECUTOR_KEYS,
  fallback,
  fragments,
  JOB_DEFAULTS_SAFE_SUBSET,
  jobDefaults,
  type Pass,
  type PassFn,
  PassRegistry,
  params,
  retry,
  runPasses,
  sortPasses,
} from "./passes/index.js";
export {
  ACTIO_SCHEMA_URL,
  actioSchema,
  actioSchemaJson,
  actioSchemaPath,
  SCHEMA_MODELINE,
} from "./schema.js";
export {
  type BuildSourceMapOptions,
  buildSourceMap,
  resolveGeneratedLine,
  type SourceMap,
  type SourceMapping,
} from "./sourcemap.js";
export {
  type NativeDependencies,
  type NativeDependencyEntry,
  type TranspileOptions,
  type TranspileResult,
  transpile,
} from "./transpile.js";
export { validateWorkflowYaml } from "./validate.js";
