import type { Diagnostic } from "./diagnostics.js";
import { emitYaml, generatedHeader } from "./emit.js";
import { parseActio } from "./parser.js";
import { type Pass, createRegistry, runPasses } from "./passes/index.js";
import { type SourceMap, buildSourceMap, resolveGeneratedLine } from "./sourcemap.js";
import { validateWorkflowYaml } from "./validate.js";

export interface TranspileOptions {
  /** File name used in diagnostics and the generated banner. Default "<input>". */
  fileName?: string;
  /** Prepend the "generated by Actio" banner. Default true. */
  header?: boolean;
  /** Validate generated YAML against GitHub's workflow schema. Default true. */
  validate?: boolean;
  /** Extra transform passes merged into the built-in pipeline (ordered by `runsAfter`). */
  passes?: Pass[];
  /** Produce a source map and remap schema diagnostics back to source. Default false. */
  sourceMap?: boolean;
}

export interface TranspileResult {
  /** True when there are no error-severity diagnostics. */
  ok: boolean;
  /** Generated workflow YAML (always present, even if validation failed). */
  yaml: string;
  diagnostics: Diagnostic[];
  /** Generated→source line map, present only when `sourceMap` is set. */
  map?: SourceMap;
}

/** Rewrite a generated-line diagnostic range to its originating source range. */
function remapDiagnostic(diagnostic: Diagnostic, map: SourceMap): Diagnostic {
  if (!diagnostic.range) return diagnostic;
  const origin = resolveGeneratedLine(map, diagnostic.range.start.line);
  if (!origin) return diagnostic;
  const start = { line: origin.line, col: origin.col };
  return { ...diagnostic, range: { start, end: start } };
}

/** Compile a single `.actio.yml` source string into standard GitHub Actions YAML. */
export function transpile(source: string, options: TranspileOptions = {}): TranspileResult {
  const fileName = options.fileName ?? "<input>";
  const ctx = parseActio(source, fileName);

  // Abort transforms on hard YAML syntax errors — the model is unreliable.
  const hasSyntaxError = ctx.diagnostics.some((d) => d.severity === "error");
  if (hasSyntaxError) {
    return { ok: false, yaml: "", diagnostics: ctx.diagnostics };
  }

  // Merge any caller-supplied passes into the built-in pipeline; ordering is
  // resolved by the registry from each pass's `runsAfter`.
  const passes = options.passes?.length ? createRegistry(options.passes).list() : undefined;
  runPasses(ctx, passes);

  const body = emitYaml(ctx.data, { header: false });
  const header = options.header === false ? "" : generatedHeader(fileName);
  const yaml = header + body;

  const map = options.sourceMap
    ? buildSourceMap(ctx, body, { headerLines: header ? header.split("\n").length - 1 : 0 })
    : undefined;

  const diagnostics: Diagnostic[] = [...ctx.diagnostics];
  if (options.validate !== false) {
    const schema = validateWorkflowYaml(yaml, fileName);
    diagnostics.push(...(map ? schema.map((d) => remapDiagnostic(d, map)) : schema));
  }

  const ok = !diagnostics.some((d) => d.severity === "error");
  return { ok, yaml, diagnostics, map };
}
