import {
  COERCION_MODES,
  type CoercionMode,
  coercionTrapCategory,
  coercionWarning,
} from "./coercion.js";
import type { ActioTarget } from "./config.js";
import type { Diagnostic } from "./diagnostics.js";
import { emitYaml, generatedHeader } from "./emit.js";
import { type ActionlintRunner, type LintMode, lintWorkflowYaml } from "./lint.js";
import { type ParseContext, type Path, parseActio } from "./parser.js";
import { annotate } from "./passes/annotate.js";
import { isObject, pushDiagnostic } from "./passes/helpers.js";
import { createRegistry, type Pass, runPasses } from "./passes/index.js";
import { applyPins, type PinOptions, type PinTarget } from "./passes/pin.js";
import { buildSourceMap, resolveGeneratedLine, type SourceMap } from "./sourcemap.js";
import { collectUnusedSymbolDiagnostics, type UnusedSymbolsMode } from "./unusedSymbols.js";
import { validateWorkflowYaml } from "./validate.js";

export interface NativeDependencyEntry {
  ref: string;
  sha: string;
  integrity: string;
}

export type NativeDependencies = Record<string, NativeDependencyEntry>;

export interface TranspileOptions {
  /** File name used in diagnostics and the generated banner. Default "<input>". */
  fileName?: string;
  /** Prepend the "generated by Actio" banner. Default true. */
  header?: boolean;
  /** Validate generated YAML against GitHub's workflow schema. Default true. */
  validate?: boolean;
  /**
   * Lint the generated workflow with `actionlint` and surface findings on the
   * `.actio.yml` source. `off` skips it (default); `warn` reports warnings;
   * `error` escalates findings to build failures. Distinct from `validate`,
   * which gates the schema check. A missing `actionlint` binary is skipped
   * gracefully with an informational note.
   */
  lint?: LintMode;
  /** Injectable actionlint runner (tests provide this to avoid the real binary). */
  actionlintRunner?: ActionlintRunner;
  /** Extra transform passes merged into the built-in pipeline (ordered by `runsAfter`). */
  passes?: Pass[];
  /** Produce a source map and remap schema diagnostics back to source. Default false. */
  sourceMap?: boolean;
  /**
   * Append the `actio-annotate` job that maps runtime failures back to source.
   * Requires `sourceMap`; ignored (with a warning) without it. Default false.
   */
  annotate?: boolean;
  /** Output target capability profile. Defaults to `legacy` behavior. */
  target?: ActioTarget;
  /**
   * Native workflow lock data emitted as top-level `dependencies:` for preview
   * targets. The resolver that computes this data lives in the CLI/build layer.
   */
  nativeDependencies?: NativeDependencies;
  /**
   * Global default mode for the injection-hoist security pass. Per-block
   * `injection-hoist:` knobs (root/job/step) override this. Default "fix".
   */
  injectionHoist?: "fix" | "warn" | "error" | "off";
  /**
   * Severity for dead-code diagnostics on declared-but-unreferenced `params`,
   * `fragments`, and `executors`. `off` disables the check; `warn` reports
   * warnings (default); `error` escalates them to build failures. Suppress a
   * single symbol with a `# actio-keep` comment on its declaration.
   */
  unusedSymbols?: UnusedSymbolsMode;
  /**
   * YAML type-coercion guard mode. `fix` force-quotes emitted string scalars
   * that a YAML-1.1 consumer (per-action `action.yml` parsing, the `on:` key,
   * downstream tooling) would coerce (e.g. `no`→false, `1:30`→90,
   * `2024-01-01`→Date, `1_000`→1000); `warn` leaves them unquoted and emits a
   * `yaml-coercion-trap` warning; `off` disables the guard. An in-source root
   * `coercion:` key overrides this. Default "fix".
   */
  coercion?: CoercionMode;
  /**
   * Pin-on-compile request. When set, pinnable `uses:` literals are rewritten to
   * their resolved digest after all passes run (so inline `{{ }}` refs are final);
   * `resolutions` seeds known digests and discovered targets surface in the result.
   * Network resolution lives in the CLI/build layer.
   */
  pin?: PinOptions;
}

export interface TranspileResult {
  /** True when there are no error-severity diagnostics. */
  ok: boolean;
  /** Generated workflow YAML (always present, even if validation failed). */
  yaml: string;
  diagnostics: Diagnostic[];
  /** Generated→source line map, present only when `sourceMap` is set. */
  map?: SourceMap;
  /** Pinnable `uses:` targets discovered (resolved or not); present only when `pin` is set. */
  pinTargets?: PinTarget[];
}

/** Rewrite a generated-line diagnostic range to its originating source range. */
function remapDiagnostic(diagnostic: Diagnostic, map: SourceMap): Diagnostic {
  if (!diagnostic.range) return diagnostic;
  const origin = resolveGeneratedLine(map, diagnostic.range.start.line);
  if (!origin) return diagnostic;
  const start = { line: origin.line, col: origin.col };
  return { ...diagnostic, range: { start, end: start } };
}

/**
 * Resolve the effective coercion mode and strip the in-source root `coercion:`
 * key so it never leaks into emitted YAML. Precedence: in-source key → option →
 * default `fix`. An invalid key value warns and inherits.
 */
function resolveCoercionMode(ctx: ParseContext, options: TranspileOptions): CoercionMode {
  const root = ctx.data as Record<string, unknown>;
  let rootMode: CoercionMode | undefined;
  if ("coercion" in root) {
    const value = root.coercion;
    if (typeof value === "string" && COERCION_MODES.has(value)) {
      rootMode = value as CoercionMode;
    } else {
      pushDiagnostic(
        ctx,
        "warning",
        `coercion must be one of "off" | "warn" | "fix" (got ${
          value === null ? "null" : typeof value
        }); using inherited mode`,
        ["coercion"],
        { code: "coercion-mode-invalid" },
      );
    }
    delete root.coercion;
  }
  return rootMode ?? options.coercion ?? "fix";
}

/**
 * Walk the final data tree and warn on every string scalar a YAML-1.1 consumer
 * would coerce. Mirrors the emitter's skip-key behavior: only object values and
 * array items are visited, never mapping keys (so the `on:` events key, a job id
 * like `build`, etc. are never flagged).
 */
function warnCoercionTraps(ctx: ParseContext, value: unknown, path: Path): void {
  if (Array.isArray(value)) {
    value.forEach((item, index) => {
      warnCoercionTraps(ctx, item, [...path, index]);
    });
    return;
  }
  if (isObject(value)) {
    for (const [key, child] of Object.entries(value)) warnCoercionTraps(ctx, child, [...path, key]);
    return;
  }
  if (typeof value !== "string") return;
  const category = coercionTrapCategory(value);
  if (category) {
    pushDiagnostic(ctx, "warning", coercionWarning(value, category), path, {
      code: "yaml-coercion-trap",
    });
  }
}

/** Compile a single `.actio.yml` source string into standard GitHub Actions YAML. */
export function transpile(source: string, options: TranspileOptions = {}): TranspileResult {
  const fileName = options.fileName ?? "<input>";
  const ctx = parseActio(source, fileName);

  // Abort transforms on hard YAML syntax errors — the model is unreliable.
  const hasSyntaxError = ctx.diagnostics.some((d) => d.severity === "error");
  if (hasSyntaxError) {
    return { ok: false, yaml: "", diagnostics: ctx.diagnostics };
  }

  // Annotation injection needs the source map to resolve failures at runtime.
  const wantAnnotate = options.annotate === true;
  const enableAnnotate = wantAnnotate && options.sourceMap === true;
  if (wantAnnotate && !options.sourceMap) {
    ctx.diagnostics.push({
      severity: "warning",
      source: "actio",
      file: fileName,
      message: "annotate requires sourceMap; skipping the actio-annotate job",
    });
  }

  // Merge any caller-supplied passes into the built-in pipeline; ordering is
  // resolved by the registry from each pass's `runsAfter`.
  let passes: Pass[] | undefined;
  if (options.passes?.length || enableAnnotate) {
    const registry = createRegistry(options.passes ?? []);
    if (enableAnnotate) registry.register(annotate);
    passes = registry.list();
  }
  if (options.injectionHoist !== undefined) {
    ctx.internal.injectionHoist = options.injectionHoist;
  }

  // Collect dead-code diagnostics before passes prune the declaration blocks
  // and rewrite the references that prove a symbol is live.
  const unusedDiagnostics = collectUnusedSymbolDiagnostics(ctx, options.unusedSymbols ?? "warn");

  runPasses(ctx, passes);

  if (
    options.target === "github-actions-native-dependencies-preview" &&
    options.nativeDependencies !== undefined &&
    Object.keys(options.nativeDependencies).length > 0
  ) {
    // TODO(native-deps-schema): tighten this shape to the final GitHub-native schema.
    (ctx.data as Record<string, unknown>).dependencies = options.nativeDependencies;
  }

  const pinTargets = options.pin ? applyPins(ctx, options.pin) : undefined;

  const coercion = resolveCoercionMode(ctx, options);
  if (coercion === "warn") warnCoercionTraps(ctx, ctx.data, []);

  const body = emitYaml(ctx.data, { header: false, coercion });
  const header = options.header === false ? "" : generatedHeader(fileName);
  const yaml = header + body;

  const map = options.sourceMap
    ? buildSourceMap(ctx, body, { headerLines: header ? header.split("\n").length - 1 : 0 })
    : undefined;

  const diagnostics: Diagnostic[] = [...ctx.diagnostics];
  if (options.validate !== false) {
    const schema = validateWorkflowYaml(yaml, fileName);
    diagnostics.push(...(map ? schema.map((d) => remapDiagnostic(d, map)) : schema));
  }
  if ((options.lint ?? "off") !== "off") {
    const lint = lintWorkflowYaml(
      yaml,
      fileName,
      options.lint as LintMode,
      options.actionlintRunner,
    );
    diagnostics.push(...(map ? lint.map((d) => remapDiagnostic(d, map)) : lint));
  }
  diagnostics.push(...unusedDiagnostics);

  const ok = !diagnostics.some((d) => d.severity === "error");
  return { ok, yaml, diagnostics, map, pinTargets };
}
