import type { Diagnostic } from "./diagnostics.js";
import { emitYaml } from "./emit.js";
import { parseActio } from "./parser.js";
import { type Pass, createRegistry, runPasses } from "./passes/index.js";
import { validateWorkflowYaml } from "./validate.js";

export interface TranspileOptions {
  /** File name used in diagnostics and the generated banner. Default "<input>". */
  fileName?: string;
  /** Prepend the "generated by Actio" banner. Default true. */
  header?: boolean;
  /** Validate generated YAML against GitHub's workflow schema. Default true. */
  validate?: boolean;
  /** Extra transform passes merged into the built-in pipeline (ordered by `runsAfter`). */
  passes?: Pass[];
}

export interface TranspileResult {
  /** True when there are no error-severity diagnostics. */
  ok: boolean;
  /** Generated workflow YAML (always present, even if validation failed). */
  yaml: string;
  diagnostics: Diagnostic[];
}

/** Compile a single `.actio.yml` source string into standard GitHub Actions YAML. */
export function transpile(source: string, options: TranspileOptions = {}): TranspileResult {
  const fileName = options.fileName ?? "<input>";
  const ctx = parseActio(source, fileName);

  // Abort transforms on hard YAML syntax errors — the model is unreliable.
  const hasSyntaxError = ctx.diagnostics.some((d) => d.severity === "error");
  if (hasSyntaxError) {
    return { ok: false, yaml: "", diagnostics: ctx.diagnostics };
  }

  // Merge any caller-supplied passes into the built-in pipeline; ordering is
  // resolved by the registry from each pass's `runsAfter`.
  const passes = options.passes?.length ? createRegistry(options.passes).list() : undefined;
  runPasses(ctx, passes);

  const yaml = emitYaml(ctx.data, { header: options.header, fileName });

  const diagnostics: Diagnostic[] = [...ctx.diagnostics];
  if (options.validate !== false) {
    diagnostics.push(...validateWorkflowYaml(yaml, fileName));
  }

  const ok = !diagnostics.some((d) => d.severity === "error");
  return { ok, yaml, diagnostics };
}
